### ISSUE TITLE
Query on why ssh counter increments, but nothing else

### ISSUE THREAD

**Issue by garilla2** [qeeqbox/chameleon#10]
Great product, and thanks in advance for any attention.

I notice my honey services all work, i can connect to them, but only the ssh counter is incrementing.

so I can connect to telnet for example, and you can see it reflect in the ports open window, but no increment. I'm stumped. Any ideas greatly appreciated.

![image](https://user-images.githubusercontent.com/53907749/139454291-8c0203f9-0fb6-4081-b458-2238fc914a36.png)

**Comment by giga-a** [comment]
@garilla2 thanks for opening this issue. How did you run this project? test or deploy?

**Comment by garilla2** [comment]
deploy mode

**Comment by garilla2** [comment]
Looks like no services are reporting now. Something to do with the IP and routing. All I did was install preqeqs and run.sh with the deploy feature on two machines. same issue.
I'm going to move onto another product, thanks very much. Possibly issue with installing on debian.
