### ISSUE TITLE
Templating [IP]  Error Updating Options pq: database "chameleon" does not exist

### ISSUE THREAD

**Issue by muzammilmian** [qeeqbox/chameleon#13]
I deployed current project on raspberry pie 4 but got error in "pip3 install postgresql", after reading Microsoft's documentation, I came to a solution by adding line `RUN apt-get install freetds-dev -y` in honeypot docker file.
I installed docker-compose using pip3 command because using curl or apt-get install command didn't work. So after all this, there came an error which states that database named chameleon doesn't exist. I cross checked it by looking into postgresql's container and there was no database named chameleon. Looking forward for solution.
Following is the attached pictures of error.

![error1](https://user-images.githubusercontent.com/74231990/147958913-ed1b4b70-b986-4b33-a856-3de6f82a5bd1.png)

![terminal](https://user-images.githubusercontent.com/74231990/147958495-e7d3df97-deed-423a-9e30-a57794bf0b54.png)

Thanks

**Comment by giga-a** [comment]
Fixed, let me know if the new update works or not

**Comment by muzammilmian** [comment]
Thanks a lot, it is working fine now 
Can you please guide, if I want to run honeypots on raspberry pie and postgres, grafana on the other machine, which configurations do I need to change?
