### ISSUE TITLE
rsa error during docker execution/install

### ISSUE THREAD

**Issue by Yahoodle** [qeeqbox/chameleon#3]
This is a great looking product.

When I run the docker 'm getting the following error:

Downloading https://files.pythonhosted.org/packages/2d/d3/41b3db87f262debadb153900d4e6f8d61aa87187dd6fedd855ed24e8526d/rsa-4.7.1.tar.gz
rsa requires Python '>=3.5, <4' but the running Python is 2.7.17
The command '/bin/sh -c pip install scapy netifaces pyftpdlib sqlalchemy pyyaml paramiko==2.7.1 impacket twisted rdpy==1.3.2 psutil requests redis mysql-connector-python pygments' returned a non-zero code: 1

Seems like the installer is executing at python2.7 and so it wont install rsa which requires new python.

Any ideas on this?

**Comment by giga-a** [comment]
Hey! Thanks for submitting this issue

You are right, [I just fixed that by moving RUN pip install -Iv rsa==4.0 before installing rdpy package](https://github.com/qeeqbox/chameleon/blob/master/honeypot/Dockerfile) 

Would you be able to check?

**Comment by KoalaWSMTW** [comment]
Hi !
I just tried today and it doesn't seem to work with pip install rsa before: /

![Capture-20210308125056-2342x173](https://user-images.githubusercontent.com/49360560/110317823-f0a15580-800c-11eb-8292-18739a3fbd3d.png)

**Comment by giga-a** [comment]
Hi @KoalaWSMTW - Thank you so much for reporting that
I have fixed that! - would you be able to re-download and check?

```
git clone https://github.com/qeeqbox/chameleon.git
cd chameleon
chmod +x ./run.sh
./run.sh auto_configure_test
```

**Comment by giga-a** [comment]
My Dedicated Testing System (Macaw) will start testing this project
Do not forgot to check the rest of the projects, thank you!! 🛵
