### ISSUE TITLE
log to file

### ISSUE THREAD

**Issue by Sparkxxx** [qeeqbox/chameleon#5]
Hi and thank your for this project,

Is it possible to get a log file/output like syslog from the honeypots? 
I plan to use chameleon on the internal network and I have centralised logging that would alert when there are failed logins.

Thank you

**Comment by giga-a** [comment]
Hey @Sparkxxx,

I can make that happen, but what about my other project `Honeypots`? 

`Chameleon` is built on top of `Honeypots`, and it's super easy to set it up!

You can setup all sort of honeypots and output the logs to file, terminal or both

```bash
pip3 install honeypots
honeypots --setup ssh --config config.json

config.json
{
    "logs":"file,terminal",
    "logs_location":"/temp/honeypots_logs/"
    "honeypots": {
        "ssh": {
            "port": 22,
            "ip": "0.0.0.0",
            "username": "test",
            "password": "test"
            }
        }
}
```

**Comment by Sparkxxx** [comment]
Thanks for the reply, 
Using "logs":"db,file", works but the format of the log is not compatible with syslog so it's not much use without a syslog-ng filter/parser.
Regarding honeypots I've upgraded the chameleon container with the latest version from honeypots-Dockerfile to the latest version 
``` RUN pip3 install honeypots==0.25 ```
instead of 0.23 which was the default one but I have not tested functionality yet.
I prefer using docker since it would not require maintaining python processes on vms running docker containers, it makes more sense for me.
My scenario is that I have a VM with docker-compose chameleon and nobody should touch that host. 
When this happens I would like to have the attempt in syslog format so that I can act upon it, and it would be great if we could use the docker syslog driver directly to redirect stdout:
```     logging:
      driver: syslog
      options:
        syslog-address: "udp://10.1.0.x:514"
        tag: "honeypots"
```
Thanks

**Comment by giga-a** [comment]
@Sparkxxx 

> Using "logs":"db,file", works but the format of the log is not compatible with syslog so it's not much use without a syslog-ng filter/parser.

Would you be able to share your syslog-ng config file?

> Regarding honeypots I've upgraded the chameleon container with the latest version from honeypots-Dockerfile to the latest version
> RUN pip3 install honeypots==0.25
> instead of 0.23 which was the default one but I have not tested functionality yet.
> I prefer using docker since it would not require maintaining python processes on vms running docker containers, it makes more sense for me.

I have pushed many updates and now you can specify syslog server in the config file. Also, I have added a syslog server to test that functionality if you run the project with `./run.sh test `

```json
    "syslog_address":"udp://syslog:514",
    "syslog_facility":3,
```

> Couldn't find much info on honeypots either and searching the web I found some references to chameleon honeypots
> https://owasp.org/www-pdf-archive/GOD17-Chameleon.pdf
> https://www.tu-braunschweig.de/index.php?eID=dumpFile&t=f&f=74776&token=78405aa9f5db4f5c28b1c071af0e27fb8893c2b7 , are you affiliated, is it the same project or behavior expected from this project?

No, the ones you listed above are different (You won't be able to find much information about QeeqBox projects because they were closed-source)

Let me know if the new updates make sense or not!
