### ISSUE TITLE
E : Unable to locate package python-psycopg2

### ISSUE THREAD

**Issue by alez404** [qeeqbox/chameleon#7]
hi
im using ubuntu 18.04
after runnig run.sh when i choose **Deploy (7)**  i get an error of **Unable to locate package python-psycopg2**
i get same on ubuntu 20.04 too
full log : 

root@ubuntu:~/chameleon# ./run.sh deploy

QeeqBox Chameleon v2021.V.02.05 starter script -> https://github.com/qeeqbox/Chameleon
Current servers (DNS, HTTP Proxy, HTTP, HTTPS, SSH, POP3, IMAP, STMP, RDP, VNC, SMB, SOCK5, TELNET and Postgres)`

[x] Install & update pre-requirements
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Fetched 252 kB in 4s (68.6 kB/s)
Reading package lists... Done
[x] Init deploy
[x] Install & update requirements
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Err:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Fetched 163 kB in 15s (10.9 kB/s)
Reading package lists... Done
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633  100   633    0     0    536      0  0:00:01  0:00:01 --:--:--   536
100 16.7M  100 16.7M    0     0   258k      0  0:01:06  0:01:06 --:--:--  202k
/usr/local/bin/docker-compose
Good
/usr/bin/docker
Good
[x] Fixing ports
Creating network "chameleon_backend" with the default driver
Creating network "chameleon_frontend" with the default driver
Building honeypots
Step 1/8 : FROM python:3.8
 ---> 79372a158581
Step 2/8 : RUN echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections &&        echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections &&         apt-get update -y && apt-get install -y iptables-persistent tcpdump nmap iputils-ping python-psycopg2 lsof psmisc dnsutils libffi-dev libssl-dev
 ---> Running in 0f6ba4d3b433
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 Packages [8180 kB]
Get:4 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [70.3 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2300 B]
Fetched 8452 kB in 5min 20s (26.4 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-psycopg2
ERROR: Service 'honeypots' failed to build: The command '/bin/sh -c echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections &&   echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections &&         apt-get update -y && apt-get install -y iptables-persistent tcpdump nmap iputils-ping python-psycopg2 lsof psmisc dnsutils libffi-dev libssl-dev' returned a non-zero code: 100

Choose an option:
1) Setup requirements (docker, docker-compose)
2) Test the project (All servers and Sniffer)
7) Run deploy
8) Run dev
9) Run test
>>

**Comment by giga-a** [comment]
Hey, I'm looking..
